config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('website.urls', namespace="website")),
]

website/urls.py
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap
from .views import (TestView, AppointmentView, IndexView, ContactView, AboutView, ServicesView, PortfolioView, PricingView, BlogView, CarouselView)

sitemaps = {
    "static": StaticViewSitemap,
}

app_name = "website"

urlpatterns = [
    # Add a comment for better readability
    # ------------------------------------
    # homepage view
    path('', IndexView.as_view(), name="home"),

    # Test view
    path("test.html", TestView.as_view(), name="testnew"),

    # appointment view
    path('appointment.html', AppointmentView.as_view(), name="appointment"),

    # contact view
    path('kontakt.html', ContactView.as_view(), name="contact"),

    # about view
    path('about.html', AboutView.as_view(), name="about"),

    # services view
    path('services.html', ServicesView.as_view(), name="services"),

    # portfolio view
    path('portfolio.html', PortfolioView.as_view(), name="portfolio"),

    # pricing view
    path('pricing.html', PricingView.as_view(), name="pricing"),

    # blog view
    path('stellenangebote.html', BlogView.as_view(), name="blog"),

    # carousel view
    path('carousel.html', CarouselView.as_view(), name="carousel"),

    # sitemap view
    path("sitemap.xml", sitemap,{"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
]

config/models.py
from django.db import models

# Create your models here.

class CarouselImage(models.Model):
    image = models.ImageField(upload_to='carousel_images/')
    caption = models.CharField(max_length=255, blank=True)

website/models.py
from django.db import models

# Create your models here.

class CarouselImage(models.Model):
    image = models.ImageField(upload_to='carousel_images/')
    caption = models.CharField(max_length=255, blank=True)
    

config/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from .models import CarouselImage

customer_info = {
    "cName": "A N A S S E",
    "cSlogan": "Hotelservice & Dienstleistungen",
    "cInH": "InH. Anasse Boukari",
    "cAddr": "Koblenzer straße 31",
    "cPLZ": "60327",
    "cCity": "Frankfurt am Main",
    "cState": "Hessen",
    "cTel": "+49 176 638 993 63",
    "cOpnMn": "Mon-DO: 09:00 bis 18:00 Uhr",
    "cOpnFr": "FR: 09:00 bis 15:00 Uhr",
    "message_name": "message_name",
    "cWebsite": "https://anasse.de",
    "cEmail": "info@anasse.de",
    "cQuestions": "Have a Questions?",
    "cOpenHrs": "Geschäftszeiten",
    "cOpenDays": "Öffnungstage:",
    "cEmergency": "Für Notfälle",
    "cVaccation": "Ferien",
    "cWorks": "Die Art von Arbeiten, die wir ausführen",
    "cSubheading": "Sauber Räume, glückliche Gesichter",
    "cFriendly": "Wir verwenden umweltfreundliche Reinigungsprodukte für Kunden, die ökologische Reinigungslösungen bevorzugen.",
    "cMission": "Unsere Mission ist es, das vertrauenswürdigste und zuverlässigste Reinigungsunternehmen in der Region zu werden. Wir werden dies erreichen, indem wir außergewöhnliche Reinigungsdienste anbieten, umweltfreundliche Reinigungsprodukte verwenden und wettbewerbsfähige Preise anbieten.",
    
        
}
# Create your views here.
def home(request):
    return render(request, 'home.html', customer_info)

def about(request):
    return render(request, 'about.html', customer_info)

def services(request):
    return render(request, 'services.html', customer_info)

def portfolio(request):
    return render(request, 'portfolio.html', customer_info)

def pricing(request):
    return render(request, 'pricing.html', customer_info)

def blog(request):
    return render(request, 'blog.html', customer_info)

def carousel(request):
    images = CarouselImage.objects.all()
    #a = {'carousel_images': carousel_images}
    #context = customer_info.values.__new__(a.values)
    #context = {'customer_info': customer_info, 'carousel_images': carousel_images}
    return render(request, 'carousel.html', {'carousel_images': images})
    #return render(request, 'carousel.html', context)

def contact(request):
    if request.method == "POST":
        message_name = request.POST['message-name']
        message_email = request.POST['message-email']
        message = request.POST['message']
        
        # send an email
        send_mail(
            message_name, # subject
            message, # message
            message_email, # from email
            ['receiver@domain.com'] # to email
            
        )
        
        return render(request, 'contact.html', customer_info)
    
    else:
        return render(request, 'contact.html', customer_info)

def appointment(request):
    if request.method == "POST":
        message_name = request.POST['message-name']
        message_email = request.POST['message-email']
        message = request.POST['message']
        
        # send an email
        send_mail(
            message_name, # subject
            message, # message
            message_email, # from email
            ['receiver@domain.com'] # to email
            
        )
        
        return render(request, 'appointment.html', {'message_name': message_name})
    
    else:
        return render(request, 'home.html', customer_info)

website/views.py
from django.views.generic import TemplateView, ListView
from django.shortcuts import get_object_or_404, render
from django.core.mail import send_mail
from .models import CarouselImage
from django.urls import reverse
from django.views import generic
from django.contrib.sitemaps import Sitemap
from .mixin import GermanMixin


class AppointmentView(GermanMixin, TemplateView):
    template_name = "appointment.html"
    

class TestView(GermanMixin, TemplateView):
    template_name = "test.html"
  

class IndexView(GermanMixin, TemplateView):
    template_name = "index.html"



class AboutView(GermanMixin, TemplateView):
    template_name = "about.html"
  

class ServicesView(GermanMixin, TemplateView):
    template_name = "services.html"
  

class PortfolioView(GermanMixin, TemplateView):
    template_name = "portfolio.html"
  

class PricingView(GermanMixin, TemplateView):
    template_name = "pricing.html"
  

class BlogView(GermanMixin, TemplateView):
    template_name = "stellenangebote.html"


class CarouselView(GermanMixin, TemplateView):
    template_name = "carousel.html"


class ContactView(GermanMixin, TemplateView):
    template_name = "kontakt.html"

    def post(self, request, *args, **kwargs):
        message_name = request.POST['message-name']
        message_email = request.POST['message-email']
        message = request.POST['message']
        
        # send an email
        send_mail(
            message_name, # subject
            message, # message
            message_email, # from email
            ['receiver@domain.com'] # to email
            
        )
   

website/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{cinfo.cName}} {{cinfo.cSlogan}}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'website/css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'website/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'website/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/style.css' %}">
</head>
<body>
    <div class="wrap">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-12 col-md d-flex align-items-center">
                    <p class="mb-0 phone"><span class="mailus">Phone no:</span> <a href="#">{{cinfo.cTel}}</a> oder <span class="mailus">email:</span> <a href="mailto://{{cinfo.cEmail}}">{{cinfo.cEmail}}</a></p>
                </div>
                <div class="col-12 col-md d-flex justify-content-md-end">
                    <div class="social-media">
                        <p class="mb-0 d-flex">
                            <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-facebook"><i class="sr-only">Facebook</i></span></a>
                            <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-twitter"><i class="sr-only">Twitter</i></span></a>
                            <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-instagram"><i class="sr-only">Instagram</i></span></a>
                            <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-dribbble"><i class="sr-only">Dribbble</i></span></a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
        <div class="container">
            <a class="navbar-brand" href="{% url 'website:home' %}">{{cinfo.cName}} <span>{{cinfo.cSlogan}}</span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="fa fa-bars"></span> Menu
            </button>
            <div class="collapse navbar-collapse" id="ftco-nav">
                {% block navigation %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active"><a href="{% url 'website:home' %}" class="nav-link">Willkommen</a></li>
                    <li class="nav-item"><a href="{% url 'website:about' %}" class="nav-link">Über uns</a></li>
                    <li class="nav-item"><a href="{% url 'website:services' %}" class="nav-link">Dienstleistung</a></li>
                    {% comment %}
                    <li class="nav-item"><a href="portfolio.html" class="nav-link">Portfolio</a></li>
                    <li class="nav-item"><a href="pricing.html" class="nav-link">Pricing</a></li> {% endcomment %}
                    <li class="nav-item"><a href="{% url 'website:blog' %}" class="nav-link">Stellenangebote</a></li>
                    <li class="nav-item"><a href="{% url 'website:contact' %}" class="nav-link">Kontakt</a></li>
                </ul>
                {% endblock navigation %}
            </div>
        </div>
    </nav>
    <!-- END nav -->
    {% block content %}

    {% endblock content %}

    <footer class="footer ftco-section">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-lg-3 mb-4 mb-md-0">
                    <h2 class="footer-heading">{{cinfo.cSlogan}}</h2>
                    <p>{{cinfo.cMission}}</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-4">
                        <li class="ftco-animate"><a href="#"><span class="fa fa-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="fa fa-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="fa fa-instagram"></span></a></li>
                    </ul>
                    {% comment %}
                </div>
                <div class="col-md-6 col-lg-3 mb-4 mb-md-0">
                    <h2 class="footer-heading">Latest News</h2>
                    <div class="block-21 mb-4 d-flex">
                        <a class="img mr-4 rounded" style="background-image: url(images/image_1.jpg);"></a>
                        <div class="text">
                            <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> Mar. 04, 2020</a></div>
                                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div> {% endcomment %}
                    {% comment %} <div class="block-21 mb-4 d-flex">
                        <a class="img mr-4 rounded" style="background-image: url(images/image_2.jpg);"></a>
                        <div class="text">
                            <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> Mar. 04, 2020</a></div>
                                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div> {% endcomment %}
                </div>
                <div class="col-md-6 col-lg-3 pl-lg-5 mb-4 mb-md-0">
                    <h2 class="footer-heading">{{cinfo.cQLinks}}</h2>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'website:home' %}" class="py-1 d-block">{{cinfo.cNHome}}</a></li>
                        <li><a href="{% url 'website:about' %}" class="py-1 d-block">{{cinfo.cNAbout}}</a></li>
                        <li><a href="{% url 'website:services' %}" class="py-1 d-block">{{cinfo.cNServices}}</a></li>
                        {% comment %}
                        <li><a href="#" class="py-1 d-block">Works</a></li>{% endcomment %}
                        <li><a href="{% url 'website:blog' %}" class="py-1 d-block">{{cinfo.cNBlog}}</a></li>
                        <li><a href="{% url 'website:contact' %}" class="py-1 d-block">{{cinfo.cNContact}}</a></li>
                    </ul>
                </div>
                <div class="col-md-6 col-lg-3 mb-4 mb-md-0">
                    <h2 class="footer-heading">{{cinfo.cQuestions}}</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon fa fa-map-marker"></span><span class="text">{{cinfo.cAddr}}, {{cinfo.cPLZ}} {{cinfo.cCity}}</span></li>
                            <li><a href="#"><span class="icon fa fa-phone"></span><span class="text">{{cinfo.cTel}}</span></a></li>
                            <li><a href="#"><span class="icon fa fa-paper-plane"></span><span class="text">{{cinfo.cEmail}}</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-md-12 text-center">

                    <p class="copyright">
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | <a href="https://skylinewebservice.com" target="_blank">Skyline Webservice</a> |
                    </p>
                </div>
            </div>
        </div>
    </footer>



    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>


    <script src="{% static 'website/js/jquery.min.js' %}"></script>
    <script src="{% static 'website/js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'website/js/popper.min.js' %}"></script>
    <script src="{% static 'website/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'website/js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'website/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'website/js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'website/js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'website/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'website/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'website/js/scrollax.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="{% static 'website/js/google-map.js' %}"></script>
    <script src="{% static 'website/js/main.js' %}"></script>

</body>
</html>

website/templates/blog.html
{% extends 'base.html' %}
{% load static %}

            {% block navigation %}
	        <ul class="navbar-nav ml-auto">
	        	<li class="nav-item"><a href="{% url 'website:home' %}" class="nav-link">Willkommen</a></li>
	        	<li class="nav-item"><a href="{% url 'website:about' %}" class="nav-link">Über uns</a></li>
	        	<li class="nav-item"><a href="{% url 'website:services' %}" class="nav-link">Dienstleistung</a></li>
	        	{% comment %} <li class="nav-item"><a href="portfolio.html" class="nav-link">Portfolio</a></li>
	        	<li class="nav-item"><a href="pricing.html" class="nav-link">Pricing</a></li> {% endcomment %}
	          <li class="nav-item active"><a href="{% url 'website:blog' %}" class="nav-link">Stellenangebote</a></li>
	          <li class="nav-item"><a href="{% url 'website:contact' %}" class="nav-link">Kontakt</a></li>
	        </ul>
            {% endblock navigation %}

{% block content %}            
    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'website/images/bg_2.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end">
          <div class="col-md-9 ftco-animate pb-5">
          	<p class="breadcrumbs mb-2"><span class="mr-2"><a href="index.html">Home <i class="fa fa-chevron-right"></i></a></span> <span>Blog <i class="fa fa-chevron-right"></i></span></p>
            <h1 class="mb-0 bread">Blog</h1>
          </div>
        </div>
      </div>
    </section>
		
		<section class="ftco-section">
      <div class="container">
        <div class="row d-flex">
          <div class="col-md-6 col-lg-4 d-flex ftco-animate">
            <div class="blog-entry align-self-stretch">
              <a href="blog-single.html" class="block-20 rounded" style="background-image: url('images/image_1.jpg');">
              </a>
              <div class="text mt-3 px-4">
              	<div class="posted mb-3 d-flex">
              		<div class="img author" style="background-image: url(images/person_2.jpg);"></div>
              		<div class="desc pl-3">
              			<span>Posted by John doe</span>
              			<span>04 March 2020</span>
              		</div>
              	</div>
                <h3 class="heading"><a href="#">10 Tips to clean your window</a></h3>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.</p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 d-flex ftco-animate">
            <div class="blog-entry align-self-stretch">
              <a href="blog-single.html" class="block-20 rounded" style="background-image: url('images/image_2.jpg');">
              </a>
              <div class="text mt-3 px-4">
              	<div class="posted mb-3 d-flex">
              		<div class="img author" style="background-image: url(images/person_3.jpg);"></div>
              		<div class="desc pl-3">
              			<span>Posted by John doe</span>
              			<span>04 March 2020</span>
              		</div>
              	</div>
                <h3 class="heading"><a href="#">10 Tips to clean your window</a></h3>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.</p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 d-flex ftco-animate">
            <div class="blog-entry align-self-stretch">
              <a href="blog-single.html" class="block-20 rounded" style="background-image: url('images/image_3.jpg');">
              </a>
              <div class="text mt-3 px-4">
              	<div class="posted mb-3 d-flex">
              		<div class="img author" style="background-image: url(images/person_1.jpg);"></div>
              		<div class="desc pl-3">
              			<span>Posted by John doe</span>
              			<span>04 March 2020</span>
              		</div>
              	</div>
                <h3 class="heading"><a href="#">10 Tips to clean your window</a></h3>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.</p>
              </div>
            </div>
          </div>

          <div class="col-md-6 col-lg-4 d-flex ftco-animate">
            <div class="blog-entry align-self-stretch">
              <a href="blog-single.html" class="block-20 rounded" style="background-image: url('images/image_4.jpg');">
              </a>
              <div class="text mt-3 px-4">
              	<div class="posted mb-3 d-flex">
              		<div class="img author" style="background-image: url(images/person_2.jpg);"></div>
              		<div class="desc pl-3">
              			<span>Posted by John doe</span>
              			<span>04 March 2020</span>
              		</div>
              	</div>
                <h3 class="heading"><a href="#">10 Tips to clean your window</a></h3>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.</p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 d-flex ftco-animate">
            <div class="blog-entry align-self-stretch">
              <a href="blog-single.html" class="block-20 rounded" style="background-image: url('images/image_5.jpg');">
              </a>
              <div class="text mt-3 px-4">
              	<div class="posted mb-3 d-flex">
              		<div class="img author" style="background-image: url(images/person_3.jpg);"></div>
              		<div class="desc pl-3">
              			<span>Posted by John doe</span>
              			<span>04 March 2020</span>
              		</div>
              	</div>
                <h3 class="heading"><a href="#">10 Tips to clean your window</a></h3>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.</p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 d-flex ftco-animate">
            <div class="blog-entry align-self-stretch">
              <a href="blog-single.html" class="block-20 rounded" style="background-image: url('images/image_6.jpg');">
              </a>
              <div class="text mt-3 px-4">
              	<div class="posted mb-3 d-flex">
              		<div class="img author" style="background-image: url(images/person_1.jpg);"></div>
              		<div class="desc pl-3">
              			<span>Posted by John doe</span>
              			<span>04 March 2020</span>
              		</div>
              	</div>
                <h3 class="heading"><a href="#">10 Tips to clean your window</a></h3>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.</p>
              </div>
            </div>
          </div>
        </div>
        <div class="row mt-5">
          <div class="col text-center">
            <div class="block-27">
              <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&gt;</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}

website/templates/contact.html
{% extends 'base.html' %}
{% load static %}

            {% block navigation %}
	        <ul class="navbar-nav ml-auto">
	        	<li class="nav-item"><a href="{% url 'website:home' %}" class="nav-link">Willkommen</a></li>
	        	<li class="nav-item"><a href="{% url 'website:about' %}" class="nav-link">Über uns</a></li>
	        	<li class="nav-item"><a href="{% url 'website:services' %}" class="nav-link">Dienstleistung</a></li>
	        	{% comment %} <li class="nav-item"><a href="portfolio.html" class="nav-link">Portfolio</a></li>
	        	<li class="nav-item"><a href="pricing.html" class="nav-link">Pricing</a></li> {% endcomment %}
	          <li class="nav-item"><a href="{% url 'website:blog' %}" class="nav-link">Stellenangebote</a></li>
	          <li class="nav-item active"><a href="{% url 'website:contact' %}" class="nav-link">Kontakt</a></li>
	        </ul>
            {% endblock navigation %}
{% block content %}
    <!-- END nav -->
    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'website/images/bg_2.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end">
          <div class="col-md-9 ftco-animate pb-5">
          	<p class="breadcrumbs mb-2"><span class="mr-2"><a href="index.html">Home <i class="fa fa-chevron-right"></i></a></span> <span>Contact <i class="fa fa-chevron-right"></i></span></p>
            <h1 class="mb-0 bread">Contact</h1>
          </div>
        </div>
      </div>
    </section>
		
		<section class="ftco-section bg-light">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-md-12">
						<div class="wrapper">
							<div class="row mb-5">
								<div class="col-md-3">
									<div class="dbox w-100 text-center">
				        		<div class="icon d-flex align-items-center justify-content-center">
				        			<span class="fa fa-map-marker"></span>
				        		</div>
				        		<div class="text">
					            <p><span>Address:</span> {{cAddr}}, {{cPLZ}} {{cCity}}</p>
					          </div>
				          </div>
								</div>
								<div class="col-md-3">
									<div class="dbox w-100 text-center">
				        		<div class="icon d-flex align-items-center justify-content-center">
				        			<span class="fa fa-phone"></span>
				        		</div>
				        		<div class="text">
					            <p><span>Phone:</span> <a href="tel://{{cTel}}">{{cTel}}</a></p>
					          </div>
				          </div>
								</div>
								<div class="col-md-3">
									<div class="dbox w-100 text-center">
				        		<div class="icon d-flex align-items-center justify-content-center">
				        			<span class="fa fa-paper-plane"></span>
				        		</div>
				        		<div class="text">
					            <p><span>Email:</span> <a href="mailto:{{cEmail}}">{{cEmail}}</a></p>
					          </div>
				          </div>
								</div>
								<div class="col-md-3">
									<div class="dbox w-100 text-center">
				        		<div class="icon d-flex align-items-center justify-content-center">
				        			<span class="fa fa-globe"></span>
				        		</div>
				        		<div class="text">
					            <p><span>Website</span> <a href="#">{{cWebsite}}</a></p>
					          </div>
				          </div>
								</div>
							</div>
							<div class="row no-gutters">
								<div class="col-md-7">
									<div class="contact-wrap w-100 p-md-5 p-4">
										<h3 class="mb-4">Contact Us</h3>
										<div id="form-message-warning" class="mb-4"></div> 
					      		<div id="form-message-success" class="mb-4">
					            Your message was sent, thank you!
					      		</div>
										<form method="POST" id="contactForm" name="contactForm" class="contactForm">
											<div class="row">
												<div class="col-md-6">
													<div class="form-group">
														<label class="label" for="name">Full Name</label>
														<input type="text" class="form-control" name="name" id="name" placeholder="Name">
													</div>
												</div>
												<div class="col-md-6"> 
													<div class="form-group">
														<label class="label" for="email">Email Address</label>
														<input type="email" class="form-control" name="email" id="email" placeholder="Email">
													</div>
												</div>
												<div class="col-md-12">
													<div class="form-group">
														<label class="label" for="subject">Subject</label>
														<input type="text" class="form-control" name="subject" id="subject" placeholder="Subject">
													</div>
												</div>
												<div class="col-md-12">
													<div class="form-group">
														<label class="label" for="#">Message</label>
														<textarea name="message" class="form-control" id="message" cols="30" rows="4" placeholder="Message"></textarea>
													</div>
												</div>
												<div class="col-md-12">
													<div class="form-group">
														<input type="submit" value="Send Message" class="btn btn-primary">
														<div class="submitting"></div>
													</div>
												</div>
											</div>
										</form>
									</div>
								</div>
								<div class="col-md-5 d-flex align-items-stretch">
									<div class="info-wrap w-100 p-5 img" style="background-image: url(images/about.jpg);">
				          </div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-12">
						<div id="map" class="map"></div>
					</div>
				</div>
			</div>
		</section>

    <section class="ftco-section ftco-no-pt ftco-no-pb bg-primary">
      <div class="container">
        <div class="row d-flex justify-content-center">
        	<div class="col-lg-8 py-4">
        		<div class="row">
		          <div class="col-md-6 ftco-animate d-flex align-items-center">
		            <h2 class="mb-0" style="color:white; font-size: 24px;">Subcribe to our Newsletter</h2>
		          </div>
		          <div class="col-md-6 d-flex align-items-center">
		            <form action="#" class="subscribe-form">
		              <div class="form-group d-flex">
		                <input type="text" class="form-control" placeholder="Enter email address">
		                <input type="submit" value="Subscribe" class="submit px-3">
		              </div>
		            </form>
		          </div>
	          </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}